services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8000:80"

  database:
    ports:
      - "3306:3306"
