
services:
  database:
    ports:
      - "3306:3306"

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: symfony-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
